###############################################################################
#
# Makefile for project 6
#
# Students:
# Zohar bouchnik, ID 311142293, zohar.bouchnik@mail.huji.ac.il
# Ella Duvdevan, ID 305564866, ella.duvdevan@mail.huji.ac.il
#
###############################################################################

# The "all" rule is what runs when we call "make":
# all it does is grant execution permissions for your run time executable
all:
	chmod a+x VMtranslator
